### ISSUE TITLE
Command line runner

### ISSUE THREAD

**Issue by mhart** [facebook/jstransform#22]
I'm sure this has been discussed somewhere, or on the cards at least – but I couldn't find a reference to it anywhere!

Is there a command line interface planned, either here or as a separate project?

**Comment by spikebrehm** [comment]
You could also use an i.e. `.jstransformerrc` file to specify default visitors

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mhart** [comment]
Gonna close this, I assume it's dead
