### ISSUE TITLE
Strange behaviour with underscores in classes

### ISSUE THREAD

**Issue by jareware** [facebook/jstransform#50]
I was asked to bring this to your attention:

https://github.com/facebook/react/issues/2712

Long story short: property access beginning with `_` within an ES6 class gets transformed, even if the object being accessed isn't `this.`.

Thoughts?

**Comment by jareware** [comment]
Don't suppose there's been any updates regarding this..?

**Comment by pbomb** [comment]
This has been tripping us up as well. Would love to see progress on this issue, but for now will go with the /** @preventMunge */ workaround.

**Comment by leoselig** [comment]
+1
This is really annoying

**Comment by zpao** [comment]
We won't be changing this behavior, we're pretty much at EOL of jstransform (see http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html). There is the `@preventMunge` workaround for anybody who wishes to continue using jstransform.
