### ISSUE TITLE
Error: Spread must be the final element of an element list. [need not be]

### ISSUE THREAD

**Issue by hemanth** [facebook/jstransform#52]
Examples:

```js
SpreadArray = (arr) => [1,...arr,3]
```

[Test cases](https://github.com/hemanth/es6-lab-setup/blob/master/spec/test.js#L53) work fine for `6to5` and `tracure`

**Comment by unwitting** [comment]
Can we have any clarification on this? Is it intended to be removed as a warning?

**Comment by zpao** [comment]
This is a parse error in esprima. [We're deprecating jstransform and our esprima fork](http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html) so we're very unlikely to do anything about this. I recommend using another tool like babel.

**Comment by hemanth** [comment]
:+1:
