### ISSUE TITLE
FR: support array comprehension.

### ISSUE THREAD

**Issue by hemanth** [facebook/jstransform#53]
The below code below code does not get transformed. 

```js
[ for (value of ["Harriet", "178"]) value ].join(" was ");
```

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hemanth** [comment]
/me digs to find the source of @facebook-github-bot-2

**Comment by spicyj** [comment]
jstransform isn't maintained any more, sorry. Use Babel instead.

**Comment by hemanth** [comment]
@spicyj yup, aware of it, was curious about the bot ;)

**Comment by zpao** [comment]
We're instituting a nag / autoclose bot for some projects and this one got tagged. You won't find the source for that bot, it's all internal (but if you somehow do manage to find it, please contact us at https://www.facebook.com/whitehat :wink:)

**Comment by hemanth** [comment]
@zpao Roger that :wink:
