### ISSUE TITLE
Make jstransform awesomer

### ISSUE THREAD

**Issue by zpao** [facebook/jstransform#73]
I've been talking about this with various people but I wanted to get it all out there…

We should make jstransform *the tool* all of our projects use. Right now we have `react-tools` that we ship along with `react`, which is basically just repackaging jstransform with an extra transform and commoner (which is giving file reading and `@providesModule` support). For Flow, we suggest installing react-tools so you can use `--strip-types`. We should make sure all of the capabilities we need are here in jstransform. Since react-tools is the primary vehicle for actually shipping our transforms to people who will use them, we lag by a lot. Or we have to ship special releases to appease non-react uses cases. This is all really silly. We should basically be making something that is focused on  transforms across our use cases and doesn't come as a command line util named `jsx`.

So let's make jstransform the thing.

- [ ] move JSX transform here
- [ ] open source some of our other useful transforms (trailing commas comes to mind)
- [ ] decide if `@providesModule` support is something we should do (if so, this definitely gets harder)
- [ ] consolidate options (react-tools has its own options it converts to jstransform options)
- [ ] make sure we expose the options that are sane and enable non-fb uses (eg, `@preventMunge` should be a runtime option, not just a pragma)
- [ ] see what we can do to align with other transform tools (eg babel) so we're all mostly on the same page and it's relatively easy to switch between.

**Comment by benjamn** [comment]
Is the argument against simply using Babel more that it does too much (at some performance cost), or that there are things it doesn't/can't do that jstransform does?

**Comment by zpao** [comment]
For now we want to maintain parity with what we're using internally. And we can't switch away from that for the same reasons you're familiar with :)

Realistically I'm not opposed to using babel for our stuff externally but there's always that risk that we depend on something specific one of the transforms does that the other does (breaking from spec or whatever). I'm sure we probably already have some dependencies like that.

My goal here is actually pretty selfish - I want to make it easier for people at FB to open source their JS. Minimizing the things that are different between internal and external will make that smoother.

**Comment by fkling** [comment]
:+1:

**Comment by sebmck** [comment]
> see what we can do to align with other transform tools (eg babel) so we're all
mostly on the same page and it's relatively easy to switch between.

As you'd know I'm more than open to collaboration and interopability :stuck_out_tongue_winking_eye: The compatibility is really only a one way street since you can easily migrate from jstransform/react-tools to Babel since Babel supports everything jstransform/react-tools does. Do you mean the generated code is compatible? (similar to facebook/react#2847)

On a similar note from my rough interpretation of the codebase, it seems like more complicated transforms such as those proposed in facebook/react#3226 and facebook/react#3228 would be either impossible or extremely tricky and finicky in jstransform since the transformations currently done by jstransform seem to be very shallow. I'd be interested to hear what the plan would be to implement those (whether it's using recast etc).

**Comment by zpao** [comment]
About compatibility… it's a bigger picture goal. I basically just want to minimize the friction. So that probably means generated code is compatible. It probably means configuration options are similar. But otherwise I'm not sure what exactly it would entail until we start getting more into it.

Yea, some of the ideas for transforms simply can't be done with jstransform. I'm not sure if those in particular fell into that bucket & I don't remember the details (just got this info secondhand) but you're right. Due to some internal perf constraints we haven't been able to switch to recast or something else, at least not yet. So we've eschewed some transforms entirely as a result.

**Comment by alexmingoia** [comment]
Regarding moving the JSX transform... not sure if this is relevant but I have separated the JSX transformation stuff into its own module decoupled from react but which depends on jstransform: https://github.com/alexmingoia/jsx-transform
